apiVersion: batch/v1
kind: Job
metadata:
  name: echo-command
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine
        command: 
          - echo
          - "Eder Vilela Brandão"
      restartPolicy: "OnFailure"
  ttlSecondsAfterFinished: 0
