apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: kubernetes.io/basic-auth  
data:
  username: WWFzbWlt
  password: WWFzbWlt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxc
  name: nginxc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxc
  template:
    metadata:
      labels:
        app: nginxc
    spec:
      containers:
      - image: nginx
        name: nginxc
        env:  
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: credentials
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: credentials
                key: password
        volumeMounts:
        - name: credentials
          mountPath: "/tmp"
          readOnly: true        
      volumes:
        - name: credentials
          secret:
            secretName: credentials
